services:
  - type: web
    name: universidad-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn uvpy.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: uvpy.settings
      - key: PYTHON_VERSION
        value: 3.10
