# Generated by Django 5.2.4 on 2025-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('duracion', models.CharField(blank=True, max_length=24)),
                ('titulo', models.CharField(max_length=32)),
                ('categoria', models.CharField(choices=[('P', 'Posgrado'), ('G', 'Grado'), ('L', 'Licenciatura'), ('T', 'Tecnicatura')], max_length=1)),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='carreras/')),
            ],
        ),
    ]
